drop table if exists bns_task;
drop table if exists bns_user;

create table bns_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table bns_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);

create table bns_ore (
	id bigint generated by default as identity,
	name varchar(255),
	types varchar(255) ,
	map varchar(255),
	line varchar(255),
	refurbish_Date timestamp,
	create_Date timestamp,
	modify_Date timestamp,
	user_id bigint not null,
	primary key (id)
);